#include "util.fh"
!---------------------------------------------------------------------!
! MBPT energy module.                                                  !
!                                                                     !
! This module evaluates closed-shell canonical MP2-type correlation    !
! energies from the converged RHF molecular orbitals.  The AO ERIs are !
! generated by the same closed-shell HGP/Obara-Saika recurrence used   !
! for the SCF operator, then transformed to the occupied-virtual        !
! MO blocks needed by MP2.                                             !
!---------------------------------------------------------------------!

module quick_mbpt_module

   implicit none
   private

   public :: calculate_mbpt, mbpt_energy_type
   public :: transform_ao_to_iajb, compute_mbpt_energies

   type mbpt_energy_type
      double precision :: opposite_spin = 0.0d0
      double precision :: same_spin = 0.0d0
      double precision :: canonical = 0.0d0
      double precision :: sos = 0.0d0
      double precision :: k_opposite_spin = 0.0d0
      double precision :: k_same_spin = 0.0d0
      double precision :: k_canonical = 0.0d0
      double precision :: kos = 0.0d0
      double precision :: lt_opposite_spin = 0.0d0
      double precision :: lt_same_spin = 0.0d0
      double precision :: lt_canonical = 0.0d0
      double precision :: lt_sos = 0.0d0
      double precision :: selected = 0.0d0
   end type mbpt_energy_type

contains

   subroutine calculate_mbpt()

      use quick_basis_module, only: nbasis
      use quick_calculated_module, only: quick_qm_struct
      use quick_eri_cshell_module, only: getCshellEriTensor
      use quick_files_module, only: ioutfile
      use quick_method_module, only: quick_method
      use quick_molspec_module, only: quick_molspec
      use quick_mpi_module, only: master
      use quick_timer_module, only: timer_begin, timer_end, timer_cumer
#ifdef MPIV
      use mpi
      use quick_mpi_module, only: bMPI, mpierror
#endif
      implicit none

      double precision, allocatable :: eri_ao(:,:,:,:)
      double precision, allocatable :: eri_iajb(:,:,:,:)
      integer :: nocc, nvir, nmo
      type(mbpt_energy_type) :: energies

      nocc = quick_molspec%nelec/2
      nmo = quick_qm_struct%NBSuse
      nvir = nmo - nocc

      if (master) call PrtAct(ioutfile,"Begin MBPT Calculation")

      RECORD_TIME(timer_begin%TMP2)

      if (quick_method%UNRST .or. mod(quick_molspec%nelec,2).ne.0) then
         if (master) call PrtErr(ioutfile,"MBPT currently supports closed-shell RHF references only.")
         call quick_exit(ioutfile,1)
      endif

      if (nvir.lt.1) then
         if (master) call PrtErr(ioutfile,"MBPT requires at least one virtual orbital.")
         call quick_exit(ioutfile,1)
      endif

      allocate(eri_ao(nbasis,nbasis,nbasis,nbasis))
      call getCshellEriTensor(eri_ao)

      if (master) then
         allocate(eri_iajb(nocc,nvir,nocc,nvir))
         call transform_ao_to_iajb(eri_ao,eri_iajb,nocc,nvir)
         call compute_mbpt_energies(eri_iajb,nocc,nvir,energies)
         call select_mbpt_energy(energies)
         quick_qm_struct%EMP2 = energies%selected
         call print_mbpt_energies(energies)
         deallocate(eri_iajb)
      endif

      deallocate(eri_ao)

#ifdef MPIV
      if (bMPI) call MPI_BARRIER(MPI_COMM_WORLD,mpierror)
#endif

      RECORD_TIME(timer_end%TMP2)
      timer_cumer%TMP2 = timer_cumer%TMP2 + timer_end%TMP2 - timer_begin%TMP2

      if (master) call PrtAct(ioutfile,"End MBPT Calculation")

   end subroutine calculate_mbpt

   subroutine transform_ao_to_iajb(eri_ao,eri_iajb,nocc,nvir)

      ! Transform (mu nu|lambda sigma) to the MO block (i a|j b).
      ! The four quarter transformations keep the canonical O(N^5)
      ! structure while avoiding storage of the full MO ERI tensor.
      use quick_calculated_module, only: quick_qm_struct
      implicit none

      double precision, intent(in) :: eri_ao(:,:,:,:)
      double precision, intent(out) :: eri_iajb(nocc,nvir,nocc,nvir)
      integer, intent(in) :: nocc, nvir

      double precision, allocatable :: tmp_b(:,:,:,:)
      double precision, allocatable :: tmp_j(:,:,:,:)
      double precision, allocatable :: tmp_a(:,:,:,:)
      double precision :: coeff
      integer :: nao
      integer :: a, b, i, j, mu, nu, lambda, sigma

      nao = size(eri_ao,1)

      allocate(tmp_b(nao,nao,nao,nvir))
      allocate(tmp_j(nao,nao,nocc,nvir))
      allocate(tmp_a(nao,nvir,nocc,nvir))

      tmp_b = 0.0d0
      do b=1,nvir
         do sigma=1,nao
            coeff = quick_qm_struct%co(sigma,nocc+b)
            if (abs(coeff).gt.0.0d0) tmp_b(:,:,:,b) = tmp_b(:,:,:,b) + eri_ao(:,:,:,sigma)*coeff
         enddo
      enddo

      tmp_j = 0.0d0
      do b=1,nvir
         do j=1,nocc
            do lambda=1,nao
               coeff = quick_qm_struct%co(lambda,j)
               if (abs(coeff).gt.0.0d0) tmp_j(:,:,j,b) = tmp_j(:,:,j,b) + tmp_b(:,:,lambda,b)*coeff
            enddo
         enddo
      enddo
      deallocate(tmp_b)

      tmp_a = 0.0d0
      do b=1,nvir
         do j=1,nocc
            do a=1,nvir
               do nu=1,nao
                  coeff = quick_qm_struct%co(nu,nocc+a)
                  if (abs(coeff).gt.0.0d0) tmp_a(:,a,j,b) = tmp_a(:,a,j,b) + tmp_j(:,nu,j,b)*coeff
               enddo
            enddo
         enddo
      enddo
      deallocate(tmp_j)

      eri_iajb = 0.0d0
      do b=1,nvir
         do j=1,nocc
            do a=1,nvir
               do i=1,nocc
                  do mu=1,nao
                     eri_iajb(i,a,j,b) = eri_iajb(i,a,j,b) + tmp_a(mu,a,j,b)*quick_qm_struct%co(mu,i)
                  enddo
               enddo
            enddo
         enddo
      enddo
      deallocate(tmp_a)

   end subroutine transform_ao_to_iajb

   subroutine compute_mbpt_energies(eri_iajb,nocc,nvir,energies)

      use quick_calculated_module, only: quick_qm_struct
      use quick_method_module, only: quick_method
      implicit none

      double precision, intent(in) :: eri_iajb(nocc,nvir,nocc,nvir)
      integer, intent(in) :: nocc, nvir
      type(mbpt_energy_type), intent(inout) :: energies

      double precision :: denom, inv_denom, inv_denom_lt
      double precision :: delta, coulomb, exchange
      double precision :: damp_k, damp_kos
      integer :: i, j, a, b

      energies%opposite_spin = 0.0d0
      energies%same_spin = 0.0d0
      energies%k_opposite_spin = 0.0d0
      energies%k_same_spin = 0.0d0
      energies%kos = 0.0d0
      energies%lt_opposite_spin = 0.0d0
      energies%lt_same_spin = 0.0d0

      do i=1,nocc
         do j=1,nocc
            do a=1,nvir
               do b=1,nvir
                  coulomb = eri_iajb(i,a,j,b)
                  exchange = eri_iajb(i,b,j,a)
                  denom = quick_qm_struct%E(i) + quick_qm_struct%E(j) &
                     - quick_qm_struct%E(nocc+a) - quick_qm_struct%E(nocc+b)
                  delta = -denom
                  inv_denom = 1.0d0/denom
                  inv_denom_lt = mbpt_laplace_inverse_denominator(delta)
                  damp_k = kappa_mp2_damping(delta,quick_method%kmp2_kappa)
                  damp_kos = kappa_mp2_damping(delta,quick_method%kos_mp2_kappa)

                  energies%opposite_spin = energies%opposite_spin + coulomb*coulomb*inv_denom
                  energies%same_spin = energies%same_spin + coulomb*(coulomb-exchange)*inv_denom

                  energies%k_opposite_spin = energies%k_opposite_spin &
                     + coulomb*coulomb*inv_denom*damp_k
                  energies%k_same_spin = energies%k_same_spin &
                     + coulomb*(coulomb-exchange)*inv_denom*damp_k
                  energies%kos = energies%kos &
                     + coulomb*coulomb*inv_denom*damp_kos

                  energies%lt_opposite_spin = energies%lt_opposite_spin + coulomb*coulomb*inv_denom_lt
                  energies%lt_same_spin = energies%lt_same_spin + coulomb*(coulomb-exchange)*inv_denom_lt
               enddo
            enddo
         enddo
      enddo

      energies%canonical = energies%opposite_spin + energies%same_spin
      energies%sos = quick_method%sos_mp2_scale*energies%opposite_spin
      energies%k_canonical = energies%k_opposite_spin + energies%k_same_spin
      energies%kos = quick_method%kos_mp2_scale*energies%kos
      energies%lt_canonical = energies%lt_opposite_spin + energies%lt_same_spin
      energies%lt_sos = quick_method%sos_mp2_scale*energies%lt_opposite_spin

   end subroutine compute_mbpt_energies

   double precision function kappa_mp2_damping(delta,kappa)

      ! Kappa regularization damps pair contributions with small positive
      ! orbital-energy gaps while smoothly recovering canonical MP2 as
      ! kappa -> infinity.
      implicit none

      double precision, intent(in) :: delta, kappa
      double precision :: attenuation

      attenuation = 1.0d0 - dexp(-kappa*delta)
      kappa_mp2_damping = attenuation*attenuation

   end function kappa_mp2_damping

   double precision function mbpt_laplace_inverse_denominator(delta)

      ! For positive Delta = eps_a + eps_b - eps_i - eps_j,
      ! 1/Delta = integral_0^infty exp(-Delta*t) dt.  This first
      ! LT implementation evaluates that identity exactly for each
      ! denominator, avoiding quadrature error while keeping the
      ! Laplace-transform energy expression explicit.
      implicit none

      double precision, intent(in) :: delta

      mbpt_laplace_inverse_denominator = -1.0d0/delta

   end function mbpt_laplace_inverse_denominator

   subroutine select_mbpt_energy(energies)

      use quick_method_module, only: quick_method
      implicit none

      type(mbpt_energy_type), intent(inout) :: energies

      if (quick_method%KOSMP2) then
         energies%selected = energies%kos
      elseif (quick_method%KMP2) then
         energies%selected = energies%k_canonical
      elseif (quick_method%LTSOSMP2) then
         energies%selected = energies%lt_sos
      elseif (quick_method%LTMP2) then
         energies%selected = energies%lt_canonical
      elseif (quick_method%SOSMP2) then
         energies%selected = energies%sos
      else
         energies%selected = energies%canonical
      endif

   end subroutine select_mbpt_energy

   subroutine print_mbpt_energies(energies)

      use quick_calculated_module, only: quick_qm_struct
      use quick_files_module, only: ioutfile
      use quick_method_module, only: quick_method
      implicit none

      type(mbpt_energy_type), intent(in) :: energies

      write (iOutFile,'("MP2 OPPOSITE-SPIN CORRELATION =",F20.12)') energies%opposite_spin
      write (iOutFile,'("MP2 SAME-SPIN CORRELATION     =",F20.12)') energies%same_spin
      write (iOutFile,'("SECOND ORDER ENERGY           =",F20.12)') energies%canonical
      write (iOutFile,'("EMP2                          =",F20.12)') quick_qm_struct%Etot+energies%canonical

      if (quick_method%SOSMP2 .or. quick_method%LTSOSMP2) then
         write (iOutFile,'("SOS-MP2 CORRELATION           =",F20.12)') energies%sos
         write (iOutFile,'("ESOS-MP2                      =",F20.12)') quick_qm_struct%Etot+energies%sos
      endif

      if (quick_method%KMP2 .or. quick_method%KOSMP2) then
         write (iOutFile,'("K-MP2 OPPOSITE-SPIN           =",F20.12)') energies%k_opposite_spin
         write (iOutFile,'("K-MP2 SAME-SPIN               =",F20.12)') energies%k_same_spin
         write (iOutFile,'("K-MP2 CORRELATION             =",F20.12)') energies%k_canonical
         write (iOutFile,'("EK-MP2                        =",F20.12)') quick_qm_struct%Etot+energies%k_canonical
      endif

      if (quick_method%KOSMP2) then
         write (iOutFile,'("KOS-MP2 CORRELATION           =",F20.12)') energies%kos
         write (iOutFile,'("EKOS-MP2                      =",F20.12)') quick_qm_struct%Etot+energies%kos
      endif

      if (quick_method%LTMP2 .or. quick_method%LTSOSMP2) then
         write (iOutFile,'("LT-MP2 CORRELATION            =",F20.12)') energies%lt_canonical
         write (iOutFile,'("ELT-MP2                       =",F20.12)') quick_qm_struct%Etot+energies%lt_canonical
      endif

      if (quick_method%LTSOSMP2) then
         write (iOutFile,'("LT-SOS-MP2 CORRELATION        =",F20.12)') energies%lt_sos
         write (iOutFile,'("ELT-SOS-MP2                   =",F20.12)') quick_qm_struct%Etot+energies%lt_sos
      endif

      if (quick_method%SOSMP2 .or. quick_method%KMP2 .or. quick_method%KOSMP2 .or. &
          quick_method%LTMP2 .or. quick_method%LTSOSMP2) then
         write (iOutFile,'("SELECTED MBPT CORRELATION     =",F20.12)') energies%selected
         write (iOutFile,'("SELECTED MBPT ENERGY          =",F20.12)') quick_qm_struct%Etot+energies%selected
      endif

   end subroutine print_mbpt_energies

end module quick_mbpt_module
